name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Release Please
        uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
          skip-labeling: true

  build-and-push:
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - linux/amd64
          - darwin/arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up environment
        run: |
          echo "TAG=${{ needs.release-please.outputs.tag_name }}" >> $GITHUB_ENV
          echo "REGISTRY=ghcr.io" >> $GITHUB_ENV
          echo "NAMESPACE=${{ github.repository_owner }}" >> $GITHUB_ENV
          echo "REPOSITORY=${{ github.event.repository.name }}/tools" >> $GITHUB_ENV

      - name: Set up ORAS
        uses: oras-project/setup-oras@v1
        with:
          version: 1.3.0-beta.3

      - name: Install dependencies
        run: |
          # Install jq
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Login to GitHub Container Registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | oras login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push ORAS artifacts
        run: |
          # Set platform-specific variables
          PLATFORM="${{ matrix.platform }}"
          OS=$(echo $PLATFORM | cut -d'/' -f1)
          ARCH=$(echo $PLATFORM | cut -d'/' -f2)

          # Export for build script
          export PLATFORMS="$PLATFORM"
          export TAG="${{ needs.release-please.outputs.tag_name }}"
          export REGISTRY="ghcr.io"
          export NAMESPACE="${{ github.repository_owner }}"
          export REPOSITORY="${{ github.event.repository.name }}/tools"

          # Set BUILD_OS and BUILD_ARCH for single platform build
          export BUILD_OS="$OS"
          export BUILD_ARCH="$ARCH"

          # Run build script - it will push with temporary tags
          ./bin/build.sh

  create-manifest-index:
    needs: [release-please, build-and-push]
    if: ${{ needs.release-please.outputs.release_created }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up ORAS
        uses: oras-project/setup-oras@v1
        with:
          version: 1.3.0-beta.3

      - name: Login to GitHub Container Registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | oras login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Create multi-platform manifest index
        run: |
          TAG="${{ needs.release-please.outputs.tag_name }}"
          REGISTRY="ghcr.io"
          NAMESPACE="${{ github.repository_owner }}"
          REPOSITORY="${{ github.event.repository.name }}/tools"
          
          # The build.sh script pushed temporary tags, we need to find them
          # They follow the pattern: ${TAG}-temp-${os}-${arch}-${PID}
          # Since we can't predict the PID, we'll look for tags that start with ${TAG}-temp-
          
          echo "Looking for temporary platform tags..."
          TEMP_TAGS=()
          
          # Try to find the temporary tags (they should exist from the build jobs)
          for platform in "linux-amd64" "darwin-arm64"; do
            # List tags and find the most recent temp tag for this platform
            TEMP_TAG=$(oras repo tags "${REGISTRY}/${NAMESPACE}/${REPOSITORY}" | grep "^${TAG}-temp-${platform}-" | head -1)
            if [ -n "$TEMP_TAG" ]; then
              TEMP_TAGS+=("$TEMP_TAG")
              echo "Found temporary tag: $TEMP_TAG"
            else
              echo "Warning: Could not find temporary tag for ${platform}"
            fi
          done
          
          if [ ${#TEMP_TAGS[@]} -eq 2 ]; then
            echo "Creating manifest index with tag: ${TAG}"
            
            # Create the manifest index
            oras manifest index create "${REGISTRY}/${NAMESPACE}/${REPOSITORY}:${TAG}" "${TEMP_TAGS[@]}" \
              --annotation "org.opencontainers.image.title=UDS k3d Cilium Tools" \
              --annotation "org.opencontainers.image.description=CLI tools for UDS k3d Cilium deployment (multi-platform)" \
              --annotation "org.opencontainers.image.version=${TAG}" \
              --annotation "org.opencontainers.image.source=https://github.com/${{ github.repository }}" \
              --annotation "org.opencontainers.artifact.created=$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
            
            echo "✅ Created multi-platform manifest index: ${REGISTRY}/${NAMESPACE}/${REPOSITORY}:${TAG}"
            
            # Clean up temporary tags
            echo "Cleaning up temporary tags..."
            for temp_tag in "${TEMP_TAGS[@]}"; do
              if oras manifest delete "${REGISTRY}/${NAMESPACE}/${REPOSITORY}:${temp_tag}" --force; then
                echo "✓ Deleted temporary tag: ${temp_tag}"
              else
                echo "⚠️  Failed to delete temporary tag: ${temp_tag}"
              fi
            done
          else
            echo "❌ Could not find all temporary platform tags"
            exit 1
          fi

  create-release-artifacts:
    needs: [release-please, create-manifest-index]
    if: ${{ needs.release-please.outputs.release_created }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up ORAS
        uses: oras-project/setup-oras@v1
        with:
          version: 1.3.0-beta.3

      - name: Login to GitHub Container Registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | oras login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Pull and package artifacts
        run: |
          TAG="${{ needs.release-please.outputs.tag_name }}"
          REGISTRY="ghcr.io"
          NAMESPACE="${{ github.repository_owner }}"
          REPOSITORY="${{ github.event.repository.name }}/tools"

          # Pull artifacts for each platform
          for platform in linux-amd64 darwin-arm64; do
            echo "Pulling ${platform} artifacts..."
            mkdir -p "tools-${platform}"
            oras pull "${REGISTRY}/${NAMESPACE}/${REPOSITORY}:${TAG}-${platform}" \
              -o "tools-${platform}"

            # Create tarball
            tar -czf "uds-tools-${TAG}-${platform}.tar.gz" -C "tools-${platform}" .
          done

          # Create checksums
          sha256sum uds-tools-*.tar.gz > checksums.txt

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.release-please.outputs.tag_name }}
          files: |
            uds-tools-*.tar.gz
            checksums.txt
            bin/install.sh
            bin/use-tools-artifact.sh

      - name: Update release notes
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.release-please.outputs.tag_name }}
          append_body: true
          body: |

            ## Installation

            ### Quick Install (Recommended)
            ```bash
            curl -sL https://github.com/${{ github.repository }}/releases/download/${{ needs.release-please.outputs.tag_name }}/install.sh | bash
            ```

            ### Manual Installation

            1. Download the appropriate tarball for your platform:
               - Linux AMD64: `uds-tools-${{ needs.release-please.outputs.tag_name }}-linux-amd64.tar.gz`
               - macOS Apple Silicon: `uds-tools-${{ needs.release-please.outputs.tag_name }}-darwin-arm64.tar.gz`

            2. Extract and install:
               ```bash
               tar -xzf uds-tools-${{ needs.release-please.outputs.tag_name }}-linux-amd64.tar.gz
               sudo cp bin/* /usr/local/bin/
               ```

            ### Using ORAS (Container Registry)
            ```bash
            # Automatic platform selection
            oras pull ghcr.io/${{ github.repository }}/tools:${{ needs.release-please.outputs.tag_name }}

            # Or specify platform explicitly
            oras pull ghcr.io/${{ github.repository }}/tools:${{ needs.release-please.outputs.tag_name }}-linux-amd64
            oras pull ghcr.io/${{ github.repository }}/tools:${{ needs.release-please.outputs.tag_name }}-darwin-arm64
            ```

            ## Included Tools
            - UDS CLI v0.27.7
            - Helm v3.18.3
            - Cilium CLI v0.18.4
            - Hubble CLI v1.17.5
            - k3d v5.8.3
            - kubectl v1.33.2
            - k9s v0.50.6

            ## Checksums
            See `checksums.txt` in the release assets for SHA256 checksums of all files.